### ISSUE TITLE
wishbone BFM - inconvenient and inconsistent naming.

### ISSUE THREAD

**Issue by m-kru** [UVVM/UVVM_Community_VIPs#3]
```
  type t_wishbone_if is record
    -- Common for slave and master interfaces
    dat_o : std_logic_vector; -- to dut
    dat_i : std_logic_vector; -- from dut

    -- Master interface
    adr_o : std_logic_vector; -- to dut, address
    cyc_o : std_logic;        -- to dut, valid bus cycle
    stb_o : std_logic;        -- to dut, chip select
    we_o : std_logic;         -- to dut, write enable
    ack_i : std_logic;        -- from dut
  end record;
```
**Inconvenience**:
`dat_o, dat_i` - you save one letter 'a' in exchange for deterioration of natural reading flow. Not worth, use `data_o, data_i`.

`adr_o` is abbreviation from the 'address' word so it should be `addr_o`.

**Inconsistency**
You use `dat_o, dat_i, adr_o`, but in other names you use for example: `data_width, addr_width`.

Summary:
Please replace all occurrences of `dat` with `data` and all `adr` with addr.

**Comment by m-kru** [comment]
@UVVM ping

**Comment by UVVM** [comment]
Hi,
I agree the names do not save much, but it follows the Wishbone specs (http://cdn.opencores.org/downloads/wbspec_b3.pdf).

Br.
Marius
