### ISSUE TITLE
Default values of setup_time and hold_time for C_WISHBONE_BFM_CONFIG_DEFAULT.

### ISSUE THREAD

**Issue by m-kru** [UVVM/UVVM_Community_VIPs#4]
Default values of both `setup_time` and `hold_time` for `C_WISHBONE_BFM_CONFIG_DEFAULT` are set to 0 ns.
They should probably be set to 2.5 ns. With 0 ns default times, wishbone BFM always fails by default with error:
```
UVVM: ***  TB_FAILURE #1  ***
UVVM:           100 ns   WISHBONE BFM
UVVM:                    wishbone_write => Failed. Boolean was false. 'Sanity check: Check that setup_time is more than 0 ns.'
```

**Comment by m-kru** [comment]
@UVVM ping

**Comment by UVVM** [comment]
Hi,

Yes they are set to 0 ns by default so the user has to set some value. However we will change this in the next release so that by default the user doesn't need to set those values unless they're needed.

Best regards,
Erick
