### ISSUE TITLE
Wishbone BFM misleading comment in the source code.

### ISSUE THREAD

**Issue by m-kru** [UVVM/UVVM_Community_VIPs#5]
In type `t_wishbone_bfm_config` there is following attribute:
`clock_period                : time;          -- Needed in the VVC`

The comment, that this is needed in the VCC is misleading. Please note, that even if you do not use VCC, but only `wishbone_*` procedures, this constraint is always checked.
For example, if user uses default value for `config`, then user must provide `clk` with 10 ns period. Otherwise transaction fails:
```
UVVM: ***  TB_ERROR #1  ***
UVVM:          82.5 ns   TB seq.
UVVM:                    check_value_in_range() => Failed. time  Was 15000000 fs. Expected between 10000000 fs and 10000000 fs
UVVM:                    checking clk period is within requirement.
```

**Comment by m-kru** [comment]
@UVVM ping

**Comment by UVVM** [comment]
Fixed
